[custom]
ruleset=JustDirect,https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/Ruleset/Evan/WeChat.list
ruleset=Advertising,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=Greenify,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=AI,https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/Ruleset/Public/AI.list
ruleset=AI,https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/rule/openai.list
ruleset=AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AI.list
ruleset=Crypto,https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/Ruleset/Public/Crypto.list
ruleset=Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=Apple Geo,https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/Ruleset/Public/AppleGeo.list
ruleset=Apple News,https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/Ruleset/Public/AppleNews.list
ruleset=Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/QuantumultX/Apple/Apple.list
ruleset=Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=Supercell,https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/Ruleset/Public/Supercell.list
ruleset=Instagram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Instagram.list
ruleset=Tiktok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/QuantumultX/TikTok/TikTok.list
ruleset=Gaming,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=Gaming,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=Gaming,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/YouTube/YouTube.list
ruleset=Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=Media,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=Final,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=JustDirect,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=JustDirect,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=JustDirect,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=JustDirect,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=JustDirect,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=JustDirect,[]GEOIP,CN
ruleset=Final,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=Current`ssid`Selected`Selected`AirPort Time Capsule=DIRECT
custom_proxy_group=Selected`select`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇺🇲 USA`[]🇯🇵 Japan`[]🇦🇺 Australia`[]🇬🇧 UK`[]✈️ Tunnel`.*
custom_proxy_group=YouTube`select`[]Current`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇦🇺 Australia`[]🇬🇧 UK`[]Selected`[]DIRECT
custom_proxy_group=Netflix`select`[]Current`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇦🇺 Australia`[]🇬🇧 UK`[]Selected`[]DIRECT
custom_proxy_group=AI`select`[]Current`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇦🇺 Australia`[]🇬🇧 UK`[]DIRECT
custom_proxy_group=Media`select`[]Current`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇦🇺 Australia`[]🇬🇧 UK`[]DIRECT
custom_proxy_group=Microsoft`select`[]Current`[]🇺🇲 USA`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇦🇺 Australia`[]🇬🇧 UK`[]DIRECT
custom_proxy_group=Apple`select`[]Current`[]🇺🇲 USA`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇦🇺 Australia`[]🇬🇧 UK`[]DIRECT
custom_proxy_group=Apple Geo`select`[]Current`[]🇺🇲 USA`[]DIRECT
custom_proxy_group=Apple News`select`[]Current`[]🇺🇲 USA`[]DIRECT
custom_proxy_group=Telegram`select`[]Current`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇦🇺 Australia`[]🇬🇧 UK`[]Selected`[]DIRECT
custom_proxy_group=Instagram`select`[]Current`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇦🇺 Australia`[]🇬🇧 UK`[]✈️ Tunnel`[]DIRECT
custom_proxy_group=Tiktok`select`[]Current`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇦🇺 Australia`[]🇬🇧 UK`[]Selected`[]DIRECT
custom_proxy_group=Gaming`select`[]Current`[]🇺🇲 USA`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇦🇺 Australia`[]🇬🇧 UK`[]DIRECT
custom_proxy_group=Supercell`select`[]Current`[]✈️ Tunnel`[]DIRECT
custom_proxy_group=Crypto`select`[]Current`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇦🇺 Australia`[]🇬🇧 UK`[]Selected`[]DIRECT
custom_proxy_group=JustDirect`select`[]DIRECT`[]Current
custom_proxy_group=Advertising`select`[]REJECT`[]DIRECT`[]Current
custom_proxy_group=Greenify`select`[]REJECT`[]DIRECT`[]Current
custom_proxy_group=Final`select`[]Current`[]DIRECT`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇦🇺 Australia`[]🇬🇧 UK`[]Selected


; custom_proxy_group=🇭🇰 HongKong`url-test`!!GROUPID=0-1!!(IEPL SZ-HK)`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=🇭🇰 HongKong`url-test`!!GROUPID=0-1!!(HKT-Detour)`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=🇯🇵 Japan`url-test`!!GROUPID=0-1!!^(?!.*VLESS_).*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,0
; custom_proxy_group=🇺🇲 USA`url-test`!!GROUPID=0-1!!(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=🇺🇲 USA`url-test`!!GROUPID=0-1!!(LA-)`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=🇸🇬 Singapore`url-test`!!GROUPID=0-1!!^(?!.*VLESS_).*(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=🇹🇼 Taiwan`url-test`!!GROUPID=0-1!!(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=🇦🇺 Australia`url-test`!!GROUPID=0-1!!(澳大利亚|澳洲|AU|Oz-)`http://www.gstatic.com/generate_204`300,,0
custom_proxy_group=🇬🇧 UK`url-test`!!GROUPID=0-1!!(UK)`http://www.gstatic.com/generate_204`300,,0
; custom_proxy_group=🇰🇷 Korea`url-test`!!GROUPID=0-1!!^(?!.*VLESS_).*(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=✈️ Tunnel`select`[]VLESS_LA1`[]Trojan_TK1`[]Trojan_SG1`[]Trojan_LA1`[]Trojan_LA2`[]Trojan_DA1`[]Trojan_KR1`[]Trojan_KR2`[]DIRECT
;设置分组标志位

enable_rule_generator=true
overwrite_origal_rules=true

clash_rule_base=https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/ConfigBase/Clash/GeneralClashConfig.yml
quanx_rule_base=https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/ConfigBase/QuantumultX/EvanQuanx.conf
