#For Personal Use Only
#For Both Clash and QuantumultX
#Winter, Yangyang, Fan

;设置规则标志位
ruleset=Advertising,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=Greenify,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=AI,https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/rule/openai.list
ruleset=AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AI.list
ruleset=Apple Geo,https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/Ruleset/Public/AppleGeo.list
ruleset=Apple News,https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/Ruleset/Public/AppleNews.list
ruleset=Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/QuantumultX/Apple/Apple.list
ruleset=Zoom,https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/Ruleset/Public/Zoom.list
ruleset=Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=Instagram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Instagram.list
ruleset=TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/QuantumultX/TikTok/TikTok.list
ruleset=YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/YouTube/YouTube.list
ruleset=Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=Media,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=Gaming,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=Gaming,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=Selected,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=JustDirect,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=JustDirect,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=JustDirect,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=JustDirect,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=JustDirect,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=JustDirect,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=JustDirect,[]GEOIP,CN
ruleset=Final,[]FINAL

;设置分组标志位
custom_proxy_group=Selected`select`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia`.*
custom_proxy_group=YouTube`select`[]Selected`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia`[]DIRECT
custom_proxy_group=Netflix`select`[]Selected`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia`[]DIRECT
custom_proxy_group=Instagram`select`[]Selected`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia`[]DIRECT
custom_proxy_group=TikTok`select`[]Selected`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia`[]DIRECT
custom_proxy_group=AI`select`[]Selected`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia`[]DIRECT
custom_proxy_group=Telegram`select`[]Selected`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia`[]DIRECT
custom_proxy_group=Media`select`[]Selected`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia`[]DIRECT
custom_proxy_group=Microsoft`select`[]DIRECT`[]Selected`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia
custom_proxy_group=Zoom`select`[]Selected`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia`[]DIRECT
custom_proxy_group=Apple`select`[]DIRECT`[]Selected`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia`[]DIRECT
custom_proxy_group=Apple Geo`select`[]DIRECT`[]Selected`[]🇺🇲 USA
custom_proxy_group=Apple News`select`[]Selected`[]🇺🇲 USA`[]DIRECT
custom_proxy_group=Gaming`select`[]Selected`[]🎮 Gaming`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia
custom_proxy_group=JustDirect`select`[]DIRECT`[]Selected
custom_proxy_group=Advertising`select`[]REJECT`[]DIRECT`[]Selected
custom_proxy_group=Greenify`select`[]REJECT`[]DIRECT`[]Selected
custom_proxy_group=Final`select`[]Selected`[]🇸🇬 Singapore`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇯🇵 Japan`[]🇺🇲 USA`[]🇬🇧 UK`[]🇪🇺 Europe`[]🌎 America`[]🌏 Asia`[]DIRECT

custom_proxy_group=🇭🇰 HongKong`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 Japan`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 USA`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|LA)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 Singapore`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇼 Taiwan`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇬🇧 UK`url-test`(UK|英国)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇪🇺 Europe`select`(德国|DE-|法国|英国|荷兰|意大利|西班牙|瑞士|瑞典)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌎 America`select`(加拿大|墨西哥|智利|巴西|哥伦比亚)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌏 Asia`select`(韩国|沙特|以色列|越南|泰国|马来西亚|菲律宾|印度|印度尼西亚|澳大利亚|土耳其|迪拜|澳门)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎮 Gaming`select`(Gaming|Games)`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=✈️ Tunnel`select`(MPLS Gaming)`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/ConfigBase/Clash/GeneralClashConfig.yml
quanx_rule_base=https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/ConfigBase/QuantumultX/GeneralQuanXConfig.conf
surfboard_rule_base=https://raw.githubusercontent.com/evansrightherecoding/weNeedthisbullshit/master/ConfigBase/Surfboard/GeneralSurfboard.conf